version: 2

jobs:
  test:
    working_directory: ~/react-template
    docker:
      - image: circleci/node:10.8-stretch
    steps:
      - checkout
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: install-node-modules
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: flow
          command: npm run flow
      - run:
          name: test
          command: npm test
#      - run:
#          name: code-coverage
#          command: './node_modules/.bin/nyc report --reporter=text-lcov'
#      - store_artifacts: # special step to save test results as as artifact
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
#      - store_test_results: # special step to upload test results for display in Test Summary
#          path: test-results.xml


workflows:
  version: 2
  test:
    jobs:
      - test
